lambda_leg:
    # Publish all joint states -----------------------------------
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 1000  

    # L Controllers ---------------------------------------
    L_hip_controller:
        type: effort_controllers/JointEffortController
        joint: L_hip_joint
        pid: {p: 100.0, i: 0.0, d: 5.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
    
    L_hip2_controller:
        type: effort_controllers/JointEffortController
        joint: L_hip2_joint
        pid: {p: 100.0, i: 0.0, d: 5.0, i_clamp_min: -1.0, i_clamp_max: 1.0}

    L_thigh_controller:
        type: effort_controllers/JointEffortController
        joint: L_thigh_joint
        pid: {p: 300.0, i: 0.0, d: 8.0, i_clamp_min: -1.0, i_clamp_max: 1.0}

    L_calf_controller:
        type: effort_controllers/JointEffortController
        joint: L_calf_joint
        pid: {p: 300.0, i: 0.0, d: 8.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
    
    L_toe_controller:
        type: effort_controllers/JointEffortController
        joint: L_toe_joint
        pid: {p: 300.0, i: 0.0, d: 8.0, i_clamp_min: -1.0, i_clamp_max: 1.0}

    # R Controllers ---------------------------------------
    R_hip_controller:
        type: effort_controllers/JointEffortController
        joint: R_hip_joint
        pid: {p: 100.0, i: 0.0, d: 5.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
    
    R_hip2_controller:
        type: effort_controllers/JointEffortController
        joint: R_hip2_joint
        pid: {p: 100.0, i: 0.0, d: 5.0, i_clamp_min: -1.0, i_clamp_max: 1.0}

    R_thigh_controller:
        type: effort_controllers/JointEffortController
        joint: R_thigh_joint
        pid: {p: 300.0, i: 0.0, d: 8.0, i_clamp_min: -1.0, i_clamp_max: 1.0}

    R_calf_controller:
        type: effort_controllers/JointEffortController
        joint: R_calf_joint
        pid: {p: 300.0, i: 0.0, d: 8.0, i_clamp_min: -1.0, i_clamp_max: 1.0}
    
    R_toe_controller:
        type: effort_controllers/JointEffortController
        joint: R_toe_joint
        pid: {p: 300.0, i: 0.0, d: 8.0, i_clamp_min: -1.0, i_clamp_max: 1.0}


joint1_effort_controller:
  type: effort_controllers/JointEffortController
  joint: L_hip_controller
  pid: {p: 2.0, i: 1.0, d: 0.1, i_clamp_min: -1.0, i_clamp_max: 1.0}
joint2_effort_controller:
  type: effort_controllers/JointEffortController
  joint: joint2
  pid: {p: 2.0, i: 1.0, d: 0.1, i_clamp_min: -1.0, i_clamp_max: 1.0}
joint3_effort_controller:
  type: effort_controllers/JointEffortController
  joint: joint3
  pid: {p: 2.0, i: 1.0, d: 0.1, i_clamp_min: -1.0, i_clamp_max: 1.0}
joint4_effort_controller:
  type: effort_controllers/JointEffortController
  joint: joint4
  pid: {p: 2.0, i: 1.0, d: 0.1, i_clamp_min: -1.0, i_clamp_max: 1.0}
joint5_effort_controller:
  type: effort_controllers/JointEffortController
  joint: joint5
  pid: {p: 2.0, i: 1.0, d: 0.1, i_clamp_min: -1.0, i_clamp_max: 1.0}
joint6_effort_controller:
  type: effort_controllers/JointEffortController
  joint: joint6
  pid: {p: 2.0, i: 1.0, d: 0.1, i_clamp_min: -1.0, i_clamp_max: 1.0}
joint7_effort_controller:
  type: effort_controllers/JointEffortController
  joint: joint7
  pid: {p: 2.0, i: 1.0, d: 0.1, i_clamp_min: -1.0, i_clamp_max: 1.0}
joint8_effort_controller:
  type: effort_controllers/JointEffortController
  joint: joint7
  pid: {p: 2.0, i: 1.0, d: 0.1, i_clamp_min: -1.0, i_clamp_max: 1.0}
joint9_effort_controller:
  type: effort_controllers/JointEffortController
  joint: joint7
  pid: {p: 2.0, i: 1.0, d: 0.1, i_clamp_min: -1.0, i_clamp_max: 1.0}
joint10_effort_controller:
  type: effort_controllers/JointEffortController
  joint: joint7
  pid: {p: 2.0, i: 1.0, d: 0.1, i_clamp_min: -1.0, i_clamp_max: 1.0}
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 10  
